#!/bin/bash
set -e

VERSION="$1"
if [ -z "$VERSION" ]; then
    echo "Usage: $0 <version>"
    echo "Example: $0 0.15.0"
    exit 1
fi

TAG="v$VERSION"
echo "🚀 Releasing version $VERSION"

# Pre-flight checks
if [ ! -d "../homebrew-macos" ]; then
    echo "❌ ../homebrew-macos directory not found."
    echo "Clone it: git clone git@github.com:sebsto/homebrew-macos.git ../homebrew-macos"
    exit 1
fi

if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) not installed. Install: brew install gh"
    exit 1
fi

# Check if this is a resume (tag exists)
if git rev-parse "$TAG" >/dev/null 2>&1; then
    echo "⏭️  Tag $TAG exists. Skipping to Homebrew update..."
    BOTTLE_SHA=$(curl -sL "https://github.com/sebsto/xcodeinstall/releases/download/$TAG/xcodeinstall-$VERSION.arm64_ventura.bottle.tar.gz" | shasum -a 256 | awk '{print $1}')
else
    # 1. Update version and build
    echo "📝 Updating version in source code"
    cat > Sources/xcodeinstall/Version.swift << EOF
// Generated by: scripts/simple-deploy/release.sh
struct Version {
    let current = "$VERSION"
}
EOF

    echo "🏗️ Building fat binary"
    swift build --configuration release --arch arm64 --arch x86_64

    # 2. Create GitHub release
    echo "🏷️ Creating GitHub release"
    git add Sources/xcodeinstall/Version.swift
    git commit -m "Bump version to $VERSION"
    git tag "$TAG"
    git push --no-verify origin main "$TAG"
    gh release create "$TAG" --generate-notes

    # 3. Create and upload bottles
    echo "📦 Creating bottles"
    mkdir -p bottles
    bottle_name="xcodeinstall-$VERSION.arm64_ventura.bottle.tar.gz"
    mkdir -p "xcodeinstall/$VERSION/bin"
    mkdir -p "xcodeinstall/$VERSION/.brew"
    cp .build/apple/Products/Release/xcodeinstall "xcodeinstall/$VERSION/bin/"
    cp LICENSE "xcodeinstall/$VERSION/" 2>/dev/null || true
    cp README.md "xcodeinstall/$VERSION/" 2>/dev/null || true
    echo '{"homebrew_version":"4.0.0","used_options":[],"unused_options":[],"built_as_bottle":true,"poured_from_bottle":false,"loaded_from_api":true,"installed_as_dependency":false,"installed_on_request":true,"changed_files":[],"time":null,"source_modified_time":null,"compiler":"clang","aliases":[],"runtime_dependencies":[],"source":{"tap":"sebsto/macos","spec":"stable","versions":{"stable":"'$VERSION'","version_scheme":0}}}' > "xcodeinstall/$VERSION/INSTALL_RECEIPT.json"
    tar -czf "bottles/$bottle_name" xcodeinstall
    rm -rf xcodeinstall

    BOTTLE_SHA=$(shasum -a 256 "bottles/$bottle_name" | awk '{print $1}')

    for platform in arm64_sonoma arm64_sequoia arm64_tahoe sonoma sequoia tahoe; do
        cp "bottles/$bottle_name" "bottles/xcodeinstall-$VERSION.$platform.bottle.tar.gz"
    done

    gh release upload "$TAG" bottles/*
    rm -rf bottles
fi

# 4. Generate Homebrew formula
echo "🍺 Generating Homebrew formula"
URL="https://github.com/sebsto/xcodeinstall/archive/refs/tags/$TAG.tar.gz"
SHA256=$(curl -sL "$URL" | shasum -a 256 | awk '{print $1}')

cat > xcodeinstall.rb << EOF
class Xcodeinstall < Formula
  desc "This is a command-line tool to download and install Apple's Xcode"
  homepage "https://github.com/sebsto/xcodeinstall"
  url "$URL"
  sha256 "$SHA256"
  license "Apache-2.0"

  bottle do
    root_url "https://github.com/sebsto/xcodeinstall/releases/download/$TAG"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, arm64_tahoe: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, ventura: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, sonoma: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, sequoia: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, tahoe: "$BOTTLE_SHA"
  end

  def install
    bin.install "xcodeinstall"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/xcodeinstall --version").chomp
  end
end
EOF

# 5. Update Homebrew tap
echo "📦 Updating Homebrew tap"
(
    cd ../homebrew-macos
    git pull --rebase origin main
    cp ../xcodeinstall/xcodeinstall.rb .
    git add xcodeinstall.rb
    git commit -m "Update xcodeinstall to $VERSION" || true
    git pull --rebase origin main
    git push --no-verify
) || {
    echo "❌ Failed to update Homebrew tap"
    echo "📝 Formula saved as xcodeinstall.rb"
    echo "To finish manually:"
    echo "  cd ../homebrew-macos"
    echo "  cp ../xcodeinstall/xcodeinstall.rb ."
    echo "  git add xcodeinstall.rb"
    echo "  git commit -m \"Update xcodeinstall to $VERSION\""
    echo "  git pull --rebase origin main"
    echo "  git push --no-verify"
    exit 1
}

rm -f xcodeinstall.rb

echo "✅ Release $VERSION completed!"
