#!/bin/bash
set -e

VERSION="$1"
if [ -z "$VERSION" ]; then
    echo "Usage: $0 <version>"
    echo "Example: $0 0.15.0"
    exit 1
fi

TAG="v$VERSION"
echo "🚀 Releasing version $VERSION"

# 1. Update version in source
echo "📝 Updating version in source code"
cat > Sources/xcodeinstall/Version.swift << EOF
// Generated by: scripts/simple-deploy/release.sh
struct Version {
    let current = "$VERSION"
}
EOF

# 2. Build fat binary
echo "🏗️ Building fat binary"
swift build --configuration release --arch arm64 --arch x86_64

# 3. Create GitHub release with binary
echo "🏷️ Creating GitHub release"
git add Sources/xcodeinstall/Version.swift
git commit -m "Bump version to $VERSION"
git tag "$TAG"
git push --no-verify origin main "$TAG"

gh release create "$TAG" --generate-notes

# Create bottle files
echo "📦 Creating bottle files"
mkdir -p bottles

# Create bottles for each platform
for platform in arm64_ventura arm64_sonoma arm64_sequoia arm64_tahoe ventura sonoma sequoia tahoe; do
    bottle_name="xcodeinstall-$VERSION.$platform.bottle.tar.gz"
    mkdir -p "xcodeinstall/$VERSION/bin"
    mkdir -p "xcodeinstall/$VERSION/.brew"
    cp .build/apple/Products/Release/xcodeinstall "xcodeinstall/$VERSION/bin/"
    cp LICENSE "xcodeinstall/$VERSION/" 2>/dev/null || true
    cp README.md "xcodeinstall/$VERSION/" 2>/dev/null || true
    echo '{"homebrew_version":"4.0.0","used_options":[],"unused_options":[],"built_as_bottle":true,"poured_from_bottle":false,"loaded_from_api":true,"installed_as_dependency":false,"installed_on_request":true,"changed_files":[],"time":null,"source_modified_time":null,"compiler":"clang","aliases":[],"runtime_dependencies":[],"source":{"tap":"sebsto/macos","spec":"stable","versions":{"stable":"'$VERSION'","version_scheme":0}}}' > "xcodeinstall/$VERSION/INSTALL_RECEIPT.json"
    tar -czf "bottles/$bottle_name" xcodeinstall
    rm -rf xcodeinstall
done

# Get bottle SHA256
BOTTLE_SHA=$(shasum -a 256 "bottles/xcodeinstall-$VERSION.arm64_ventura.bottle.tar.gz" | awk '{print $1}')

# Upload bottles
gh release upload "$TAG" bottles/*

# 4. Generate Homebrew formula
echo "🍺 Generating Homebrew formula"
URL="https://github.com/sebsto/xcodeinstall/archive/refs/tags/$TAG.tar.gz"
SHA256=$(curl -sL "$URL" | shasum -a 256 | awk '{print $1}')

cat > xcodeinstall.rb << EOF
class Xcodeinstall < Formula
  desc "This is a command-line tool to download and install Apple's Xcode"
  homepage "https://github.com/sebsto/xcodeinstall"
  url "$URL"
  sha256 "$SHA256"
  license "Apache-2.0"

  bottle do
    root_url "https://github.com/sebsto/xcodeinstall/releases/download/$TAG"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, arm64_tahoe: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, ventura: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, sonoma: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, sequoia: "$BOTTLE_SHA"
    sha256 cellar: :any_skip_relocation, tahoe: "$BOTTLE_SHA"
  end

  def install
    bin.install "xcodeinstall"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/xcodeinstall --version").chomp
  end
end
EOF

# 5. Update homebrew tap
echo "📦 Updating Homebrew tap"
if [ -d "../homebrew-macos" ]; then
    cp xcodeinstall.rb ../homebrew-macos/
    cd ../homebrew-macos
    git add xcodeinstall.rb
    git commit -m "Update xcodeinstall to $VERSION"
    git push --no-verify
    cd -
else
    echo "⚠️  ../homebrew-macos directory not found. Please copy xcodeinstall.rb manually."
fi

rm -rf bottles

echo "✅ Release $VERSION completed!"