# Generated by following instructions at
# https://betterprogramming.pub/a-step-by-step-guide-to-create-homebrew-taps-from-github-repos-f33d3755ba74
# https://medium.com/@mxcl/maintaining-a-homebrew-tap-for-swift-projects-7287ed379324

class Xcodeinstall < Formula
  desc "This is a command-line tool to download and install Apple's Xcode"
  homepage "https://github.com/sebsto/xcodeinstall"
  url "https://github.com/sebsto/xcodeinstall/archive/refs/tags/v0.11.7.tar.gz"
  sha256 "23bf9f9184c2ec8a8e71bb45a85be99476f879b68112bf1bc3d3946540ddd396"
  license "Apache-2.0"

  # insert bottle definition here
  bottle do
    root_url "https://github.com/sebsto/xcodeinstall/releases/download/v0.11.7"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "a907d66579e31950b5e39e403da47aaa391bd0c83eb028d60bd98b2927afbe67"
    sha256 cellar: :any_skip_relocation, arm64_sonoma: "a907d66579e31950b5e39e403da47aaa391bd0c83eb028d60bd98b2927afbe67"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "a907d66579e31950b5e39e403da47aaa391bd0c83eb028d60bd98b2927afbe67"
    sha256 cellar: :any_skip_relocation, ventura: "a907d66579e31950b5e39e403da47aaa391bd0c83eb028d60bd98b2927afbe67"
    sha256 cellar: :any_skip_relocation, sonoma: "a907d66579e31950b5e39e403da47aaa391bd0c83eb028d60bd98b2927afbe67"
    sha256 cellar: :any_skip_relocation, sequoia: "a907d66579e31950b5e39e403da47aaa391bd0c83eb028d60bd98b2927afbe67"
  end

  def install
    system "./scripts/deploy/build_fat_binary.sh"
    bin.install ".build/apple/Products/Release/xcodeinstall"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/xcodeinstall --version").chomp
  end
end
