//
//  CLIMain.swift
//  xcodeinstall
//
//  Created by Stormacq, Sebastien on 18/07/2022.
//

import ArgumentParser
import Logging

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

enum CLIError: Error {
    case invalidInput
    case userCancelled
}

@main
struct MainCommand: AsyncParsableCommand {

    // arguments that are global to all commands
    struct GlobalOptions: ParsableArguments {

        @Flag(name: .shortAndLong, help: "Produce verbose output for debugging")
        var verbose = false
    }

    // arguments for Authenticate, Signout, List, and Download
    struct CloudOptions: ParsableArguments {

        @Option(
            name: [.customLong("secretmanager-region"), .short],
            help: "Instructs to use AWS Secrets Manager to store and read secrets in the given AWS Region"
        )
        var secretManagerRegion: String?

        @Option(
            name: [.customLong("profile"), .customShort("p")],
            help: "The AWS profile name to use for authentication (from ~/.aws/credentials and ~/.aws/config)"
        )
        var profileName: String?
    }

    @OptionGroup var globalOptions: GlobalOptions

    // Customize the command's help and subcommands by implementing the
    // `configuration` property.
    nonisolated static let configuration = CommandConfiguration(
        commandName: "xcodeinstall",

        // Optional abstracts and discussions are used for help output.
        abstract: "A utility to download and install Xcode",

        // Commands can define a version for automatic '--version' support.
        version: Version().current,  // generated by scripts/deploy/version.sh

        // Pass an array to `subcommands` to set up a nested tree of subcommands.
        // With language support for type-level introspection, this could be
        // provided by automatically finding nested `ParsableCommand` types.
        subcommands: [
            Authenticate.self, Signout.self, List.self,
            Download.self, Install.self, StoreSecrets.self,
        ]

        // A default subcommand, when provided, is automatically selected if a
        // subcommand is not given on the command line.
        // defaultSubcommand: List.self)
    )

    public static func XCodeInstaller(
        with deps: AppDependencies? = nil,
        for region: String? = nil,
        profileName: String? = nil,
        verbose: Bool
    ) async throws -> XCodeInstall {

        var logger = Logger(label: "xcodeinstall")
        logger.logLevel = verbose ? .debug : .error

        if let deps {
            return await XCodeInstall(log: logger, deps: deps)
        }

        // Resolve config: merge CLI args with saved settings, display info, persist
        let baseDirectory = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".xcodeinstall")
        let configHandler = await ConfigHandler(log: logger, baseDirectory: baseDirectory)
        let display = NooraDisplay()
        let resolved = try await configHandler.resolvedConfig(
            cliRegion: region,
            cliProfile: profileName,
            display: display
        )

        // Wire dependencies using resolved values
        let fileHandler = await FileHandler(log: logger)
        let urlSession = URLSession.shared

        let secrets: SecretsHandlerProtocol
        if let effectiveRegion = resolved.secretManagerRegion {
            secrets = try await SecretsStorageAWS(
                region: effectiveRegion,
                profileName: resolved.profileName,
                log: logger
            )
        } else {
            secrets = await SecretsStorageFile(log: logger)
        }

        let authenticator: AppleAuthenticatorProtocol = await AppleAuthenticator(
            secrets: secrets,
            urlSession: urlSession,
            log: logger
        )
        let downloader: AppleDownloaderProtocol = await AppleDownloader(
            secrets: secrets,
            urlSession: urlSession,
            fileHandler: fileHandler,
            log: logger
        )

        let deps = await AppDependencies(
            fileHandler: fileHandler,
            display: display,
            readLine: NooraReadLine(),
            progressBar: ProgressBar(),
            secrets: secrets,
            authenticator: authenticator,
            downloader: downloader,
            urlSessionData: urlSession,
            shell: SystemShell(),
            log: logger
        )

        return await XCodeInstall(log: logger, deps: deps)
    }
}
