//
//  CLI.swift
//  xcodeinstall
//
//  Created by Stormacq, Sebastien on 18/07/2022.
//

import ArgumentParser
import CLIlib
import Foundation
import Logging

enum CLIError: Error {
    case invalidInput
}

@main
@MainActor
struct MainCommand: AsyncParsableCommand {

    // arguments that are global to all commands
    struct GlobalOptions: ParsableArguments {

        @Flag(name: .shortAndLong, help: "Produce verbose output for debugging")
        var verbose = false
    }

    // arguments for Authenticate, Signout, List, and Download
    struct CloudOptions: ParsableArguments {

        @Option(
            name: [.customLong("secretmanager-region"), .short],
            help: "Instructs to use AWS Secrets Manager to store and read secrets in the given AWS Region"
        )
        var secretManagerRegion: String?
    }

    @OptionGroup var globalOptions: GlobalOptions

    // Customize the command's help and subcommands by implementing the
    // `configuration` property.
    nonisolated static let configuration = CommandConfiguration(
        commandName: "xcodeinstall",

        // Optional abstracts and discussions are used for help output.
        abstract: "A utility to download and install Xcode",

        // Commands can define a version for automatic '--version' support.
        version: Version.version,  // generated by scripts/version.sh

        // Pass an array to `subcommands` to set up a nested tree of subcommands.
        // With language support for type-level introspection, this could be
        // provided by automatically finding nested `ParsableCommand` types.
        subcommands: [
            Authenticate.self, Signout.self, List.self,
            Download.self, Install.self, StoreSecrets.self,
        ]

        // A default subcommand, when provided, is automatically selected if a
        // subcommand is not given on the command line.
        // defaultSubcommand: List.self)
    )

    public static func XCodeInstaller(for region: String? = nil, verbose: Bool) async throws -> XCodeInstall {
        let logger: Logger!
        if verbose {
            logger = Log.defaultLogger(logLevel: .debug, label: "xcodeinstall")
        } else {
            logger = Log.defaultLogger(logLevel: .error, label: "xcodeinstall")
        }

        var runtimeEnv = RuntimeEnvironment()
        let xci: XCodeInstall!
        if let region {
            runtimeEnv.secrets = try AWSSecretsHandler(env: runtimeEnv, region: region)
            xci = XCodeInstall(log: logger, env: runtimeEnv)
        } else {
            xci = XCodeInstall(log: logger, env: runtimeEnv)
        }
        return xci
    }
}
