//
//  CLIMain.swift
//  xcodeinstall
//
//  Created by Stormacq, Sebastien on 18/07/2022.
//

import ArgumentParser
import Logging

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif

enum CLIError: Error {
    case invalidInput
    case userCancelled
}

@main
struct MainCommand: AsyncParsableCommand {

    // arguments that are global to all commands
    struct GlobalOptions: ParsableArguments {

        @Flag(name: .shortAndLong, help: "Produce verbose output for debugging")
        var verbose = false
    }

    // arguments for Authenticate, Signout, List, and Download
    struct CloudOptions: ParsableArguments {

        @Option(
            name: [.customLong("secretmanager-region"), .short],
            help: "Instructs to use AWS Secrets Manager to store and read secrets in the given AWS Region"
        )
        var secretManagerRegion: String?

        @Option(
            name: [.customLong("profile"), .customShort("p")],
            help: "The AWS profile name to use for authentication (from ~/.aws/credentials and ~/.aws/config)"
        )
        var profileName: String?
    }

    @OptionGroup var globalOptions: GlobalOptions

    // Customize the command's help and subcommands by implementing the
    // `configuration` property.
    nonisolated static let configuration = CommandConfiguration(
        commandName: "xcodeinstall",

        // Optional abstracts and discussions are used for help output.
        abstract: "A utility to download and install Xcode",

        // Commands can define a version for automatic '--version' support.
        version: Version().current,  // generated by scripts/deploy/version.sh

        // Pass an array to `subcommands` to set up a nested tree of subcommands.
        // With language support for type-level introspection, this could be
        // provided by automatically finding nested `ParsableCommand` types.
        subcommands: [
            Authenticate.self, Signout.self, List.self,
            Download.self, Install.self, StoreSecrets.self,
        ]

        // A default subcommand, when provided, is automatically selected if a
        // subcommand is not given on the command line.
        // defaultSubcommand: List.self)
    )

    public static func XCodeInstaller(
        with deps: AppDependencies? = nil,
        for region: String? = nil,
        profileName: String? = nil,
        verbose: Bool
    ) async throws -> XCodeInstall {

        var logger = Logger(label: "xcodeinstall")
        if verbose {
            logger.logLevel = .debug
        } else {
            logger.logLevel = .error
        }

        if let deps {
            return await XCodeInstall(log: logger, deps: deps)
        }

        // Load saved config
        let baseDirectory = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".xcodeinstall")
        let configHandler = await ConfigHandler(log: logger, baseDirectory: baseDirectory)
        let savedConfig = await configHandler.loadConfig()

        // Merge CLI args with saved config (CLI takes precedence)
        let effectiveRegion = region ?? savedConfig?.secretManagerRegion
        let effectiveProfile = profileName ?? savedConfig?.profileName

        // Display info message for loaded (non-overridden) settings
        let display = NooraDisplay()
        if effectiveRegion != nil || effectiveProfile != nil {
            var savedParts: [String] = []
            if let r = effectiveRegion, region == nil {
                savedParts.append("-s \(r)")
            }
            if let p = effectiveProfile, profileName == nil {
                savedParts.append("-p \(p)")
            }
            if !savedParts.isEmpty {
                await display.display(
                    "Using saved settings: \(savedParts.joined(separator: " "))",
                    style: .info
                )
            }
        }

        // Save config if CLI args provided (merge with existing)
        if region != nil || profileName != nil {
            let newConfig = PersistentConfig(
                secretManagerRegion: region ?? savedConfig?.secretManagerRegion,
                profileName: profileName ?? savedConfig?.profileName
            )
            try? await configHandler.saveConfig(newConfig)
            logger.debug("Saved config")
        }

        let fileHandler = await FileHandler(log: logger)
        let urlSession = URLSession.shared

        var secrets: SecretsHandlerProtocol
        var authenticator: AppleAuthenticatorProtocol
        var downloader: AppleDownloaderProtocol

        if let effectiveRegion {
            let awsSecrets = try await SecretsStorageAWS(
                region: effectiveRegion,
                profileName: effectiveProfile,
                log: logger
            )
            secrets = awsSecrets
        } else {
            secrets = await SecretsStorageFile(log: logger)
        }

        authenticator = await AppleAuthenticator(secrets: secrets, urlSession: urlSession, log: logger)
        downloader = await AppleDownloader(
            secrets: secrets,
            urlSession: urlSession,
            fileHandler: fileHandler,
            log: logger
        )

        let deps = await AppDependencies(
            fileHandler: fileHandler,
            display: display,
            readLine: NooraReadLine(),
            progressBar: ProgressBar(),
            secrets: secrets,
            authenticator: authenticator,
            downloader: downloader,
            urlSessionData: urlSession,
            shell: SystemShell(),
            log: logger
        )

        return await XCodeInstall(log: logger, deps: deps)
    }
}
